In [2]:
using CSV

In [3]:
using DataFrames

In [4]:
using DataFramesMeta

In [5]:
using Statistics

In [6]:
stud=DataFrame(CSV.File("./csv/stud.csv")) # lukm_students.csv

1891×6 DataFrame
  Row │ id      course  studentNumber  password  lastName  callName
      │ Int64   Int64   String15       String7   String31  String31
──────┼──────────────────────────────────────────────────────────────
    1 │ 505926     675  A00892710      Y86H      Sangha    Amit
    2 │ 542150     675  A00804126      P64N      Conconi   Katie
    3 │ 373971     675  A00804133      V68S      Flaa      Erik
    4 │ 658468     675  A00861304      J24R      Ly        Amy
    5 │ 946387     675  A00884171      O72X      Smith     Randy
    6 │ 127232     675  A00914659      T53O      Matias    Reiner
    7 │ 911293     675  A00927540      X46W      Liu       Celina
    8 │ 377866     675  A00930461      D22M      Dhillon   Lucky
    9 │ 387235     675  A00938050      J29V      Ward      Thomas
   10 │ 467599     675  A00953822      E95V      Rogers    Wyatt
   11 │ 519908     675  A00954408      X68J      Shi       Gloria
  ⋮   │   ⋮       ⋮           ⋮           ⋮         ⋮          ⋮
 1882 │ 192723     514  37704483       L41I      Wang      Mingkai
 1883 │ 331329     514  40977852       I53J      Wang      Wensen
 1884 │ 507497     514  22213623       R85N      Wong      Hui
 1885 │ 227667     514  17557760       E40B      Yang      Trafaline
 1886 │ 769815     514  27610260       R96U      Ye        Ryan
 1887 │ 230494     514  22250328       A97C      Zeng      Sabrina
 1888 │ 488081     514  44818177       G05O      Zhang     Jiaxin
 1889 │ 214934     514  34099135       S94T      Zhao      Curtis
 1890 │ 539865     514  56547276       Y80F      Zhou      Xinran
 1891 │ 377532     514  40747941       P86X      Zurkovic  Nicholas
                                                    1870 rows omitted

In [22]:
p1=DataFrame(CSV.File("./csv/p338.csv")) # quiz data from acadly

71×10 DataFrame
 Row │ Student Given Name  Student Family Name  Q1 Response  Q2 Response  Q3 R ⋯
     │ String7             Int64                String3      String1      Stri ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ Student                          104689  C            A            A    ⋯
   2 │ Student                          114185  B            A            BC
   3 │ Student                          116679  C            A            A
   4 │ Student                          116824  C            A            A
   5 │ Student                          162638  C            D            A    ⋯
   6 │ Student                          205269  -            -            -
   7 │ Student                          224062  -            -            -
   8 │ Student                          251559  C            D            C
   9 │ Student                          252873  D            A            C    ⋯
  10 │ Student                          264775  -            -            -
  11 │ Student                          285042  C            D            A
  ⋮  │         ⋮                    ⋮                ⋮            ⋮            ⋱
  62 │ Student                          921724  C            D            B
  63 │ Student                          935324  C            D            A    ⋯
  64 │ Student                          937196  C            D            A
  65 │ Student                          945657  -            -            -
  66 │ Student                          951469  D            A            B
  67 │ Student                          977842  -            -            -    ⋯
  68 │ Student                          990376  C            D            A
  69 │ Student                          995966  -            -            -
  70 │ Student                          996021  C            A            B
  71 │ Student                          998581  C            D            A    ⋯
                                                   6 columns and 50 rows omitted

In [27]:
transform!(p1,Symbol("Student Family Name")=>:id) # column names of id column must be the same in both dfs

71×11 DataFrame
 Row │ Student Given Name  Student Family Name  Q1 Response  Q2 Response  Q3 R ⋯
     │ String7             Int64                String3      String1      Stri ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ Student                          104689  C            A            A    ⋯
   2 │ Student                          114185  B            A            BC
   3 │ Student                          116679  C            A            A
   4 │ Student                          116824  C            A            A
   5 │ Student                          162638  C            D            A    ⋯
   6 │ Student                          205269  -            -            -
   7 │ Student                          224062  -            -            -
   8 │ Student                          251559  C            D            C
   9 │ Student                          252873  D            A            C    ⋯
  10 │ Student                          264775  -            -            -
  11 │ Student                          285042  C            D            A
  ⋮  │         ⋮                    ⋮                ⋮            ⋮            ⋱
  62 │ Student                          921724  C            D            B
  63 │ Student                          935324  C            D            A    ⋯
  64 │ Student                          937196  C            D            A
  65 │ Student                          945657  -            -            -
  66 │ Student                          951469  D            A            B
  67 │ Student                          977842  -            -            -    ⋯
  68 │ Student                          990376  C            D            A
  69 │ Student                          995966  -            -            -
  70 │ Student                          996021  C            A            B
  71 │ Student                          998581  C            D            A    ⋯
                                                   7 columns and 50 rows omitted

In [30]:
result=innerjoin(stud,p1,on=:id) # the vlookup step the two dfs just get combined by id

66×16 DataFrame
 Row │ id      course  studentNumber  password  lastName            callName   ⋯
     │ Int64   Int64   String15       String7   String31            String31   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 306316     326  91477349       N31L      Alanes              Diana      ⋯
   2 │ 822900     326  64231848       X83D      Alberts             Rosemary
   3 │ 512477     326  95864989       B55K      Angelini            Luc
   4 │ 876778     326  61731634       V82I      Appolinary          Blaise Nsh
   5 │ 396606     326  19566439       G39Y      Ardelean            Aida       ⋯
   6 │ 290701     326  98119944       G95K      Atwater             Megan
   7 │ 251559     326  19909522       C01N      Bobyn               Alex
   8 │ 935324     326  11566502       K88A      Bockhold            Samantha
   9 │ 749981     326  25995267       F46M      Caicedo             Andres     ⋯
  10 │ 775104     326  43433200       B92J      Cao                 Andi
  11 │ 550661     326  17925579       A53X      Chang               Lucienne
  ⋮  │   ⋮       ⋮           ⋮           ⋮              ⋮                   ⋮  ⋱
  57 │ 998581     326  98139280       E82T      Tummonds            Amanda
  58 │ 761102     326  90311499       T12S      Tut                 Injot      ⋯
  59 │ 478953     326  62159470       N09R      Urban               Jessica
  60 │ 379248     326  73968497       X57Z      Weibel              Olivia
  61 │ 809742     326  60041746       J40I      White               Noah
  62 │ 601169     326  85856748       U23K      Yang                Sabrina    ⋯
  63 │ 459860     326  95107330       J80P      Zhao                Elizabeth
  64 │ 764032     326  95840245       Y05H      Bose                Anusha
  65 │ 205269     326  35188267       I49E      Smeaton-Katzenberg  Georgia
  66 │ 789794     326  57237265       W39R      Trites              Christine  ⋯
                                                  11 columns and 45 rows omitted

In [33]:
result[:,[:id,:studentNumber,:lastName,:callName,:Score]] # display results with relevant columns

66×5 DataFrame
 Row │ id      studentNumber  lastName            callName           Score
     │ Int64   String15       String31            String31           String3
─────┼───────────────────────────────────────────────────────────────────────
   1 │ 306316  91477349       Alanes              Diana              NA
   2 │ 822900  64231848       Alberts             Rosemary           12
   3 │ 512477  95864989       Angelini            Luc                8
   4 │ 876778  61731634       Appolinary          Blaise Nshiyimana  8
   5 │ 396606  19566439       Ardelean            Aida               4
   6 │ 290701  98119944       Atwater             Megan              16
   7 │ 251559  19909522       Bobyn               Alex               12
   8 │ 935324  11566502       Bockhold            Samantha           16
   9 │ 749981  25995267       Caicedo             Andres             8
  10 │ 775104  43433200       Cao                 Andi               16
  11 │ 550661  17925579       Chang               Lucienne           12
  ⋮  │   ⋮           ⋮                ⋮                   ⋮             ⋮
  57 │ 998581  98139280       Tummonds            Amanda             16
  58 │ 761102  90311499       Tut                 Injot              12
  59 │ 478953  62159470       Urban               Jessica            4
  60 │ 379248  73968497       Weibel              Olivia             12
  61 │ 809742  60041746       White               Noah               4
  62 │ 601169  85856748       Yang                Sabrina            16
  63 │ 459860  95107330       Zhao                Elizabeth          16
  64 │ 764032  95840245       Bose                Anusha             8
  65 │ 205269  35188267       Smeaton-Katzenberg  Georgia            NA
  66 │ 789794  57237265       Trites              Christine          8
                                                              45 rows omitted